version: '2.2'
services:
  init-container:
    image: alpine:latest
    volumes:
      - ./src:/src
      - ./config/ASP/config.php:/src/ASP/system/config/config.php
      - backups-volume:/src/ASP/system/backups # This volume is effectively unused since ASP doesn't allow DB backups for a remote DB, but mount it anyway to avoid errors.
      - cache-volume:/src/ASP/system/cache
      - logs-volume:/src/ASP/system/logs
      - snapshots-volume:/src/ASP/system/snapshots
      - db-volume:/var/lib/mysql
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
          set -eu

          echo "Granting nginx and php read permissions"
          find /src -type d -exec chmod 755 {} \;
          find /src -type f -exec chmod 644 {} \;

          echo "Granting php write permissions"
          find /src/ASP/system/backups -type d -exec chmod 777 {} \;
          find /src/ASP/system/backups -type f -exec chmod 666 {} \;

          find /src/ASP/system/cache -type d -exec chmod 777 {} \;
          find /src/ASP/system/cache -type f -exec chmod 666 {} \;

          find /src/ASP/system/config -type d -exec chmod 777 {} \;
          find /src/ASP/system/config -type f -exec chmod 666 {} \;

          find /src/ASP/system/logs -type d -exec chmod 777 {} \;
          find /src/ASP/system/logs -type f -exec chmod 666 {} \;

          mkdir -p /src/ASP/system/snapshots/failed
          mkdir -p /src/ASP/system/snapshots/processed
          mkdir -p /src/ASP/system/snapshots/unauthorized
          mkdir -p /src/ASP/system/snapshots/unprocessed
          find /src/ASP/system/snapshots -type d -exec chmod 777 {} \;
          find /src/ASP/system/snapshots -type f -exec chmod 666 {} \;

          echo "Granting db write permissions"
          chown -R 999:999 /var/lib/mysql

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./src:/src
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - default
    depends_on:
      - init-container
      - php

  php:
    build:
      dockerfile: Dockerfile.php.dev
    volumes:
      - ./src:/src
      - ./config/ASP/config.php:/src/ASP/system/config/config.php # Main config file. Must be writeable or else ASP will throw an exception. Customize as needed
      # - ./config/ASP/armyAbbreviationMap.php:/src/ASP/system/config/armyAbbreviationMap.php:ro  # Optional: Customize as needed if using a custom mod
      # - ./config/ASP/backendAwards.php:/src/ASP/system/config/backendAwards.php:ro              # Optional: Customize as needed if using a custom mod
      # - ./config/ASP/ranks.php:/src/ASP/system/config/ranks.php:ro                              # Optional: Customize as needed if using a custom mod
      - ./config/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./config/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - backups-volume:/src/ASP/system/backups # This volume is effectively unused since ASP doesn't allow DB backups for a remote DB, but mount it anyway to avoid errors.
      - cache-volume:/src/ASP/system/cache
      - logs-volume:/src/ASP/system/logs
      - snapshots-volume:/src/ASP/system/snapshots
    networks:
      - default
    extra_hosts:
      # For xdebug to reach the host via `host.docker.internal`. See: https://github.com/moby/moby/pull/40007#issuecomment-578729356 and https://stackoverflow.com/questions/49907308/installing-xdebug-in-docker
      # If xdebug does not work, you may need to add an iptables rule to the INPUT chain: iptables -A INPUT -i br+ -j ACCEPT
      - host.docker.internal:host-gateway
    depends_on:
      - init-container

  db:
    image: mariadb:10.8
    environment:
      - MARIADB_ROOT_PASSWORD=ascent
      # - MARIADB_USER=myuser # Uncomment this if you want to create a regular user
      # - MARIADB_PASSWORD=mypassword # Uncomment this if you want to create a regular user
      - MARIADB_DATABASE=bf2stats
    volumes:
      # Seed the database on the first run. No need to use the ASP dashboard's installer. Note that the .sql file are executed in alphabetical order of their names.
      - ./src/ASP/system/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./src/ASP/system/sql/data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro
      - db-volume:/var/lib/mysql
    networks:
      - default
    depends_on:
      - init-container

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80
    networks:
      - default

networks:
  default:

volumes:
  backups-volume:
  cache-volume:
  logs-volume:
  snapshots-volume:
  db-volume:
